_id: 672dea7e1e665f002c436c5b
title: Single Play Duels
description: Describe your new bucket
icon: account_box
primary: name
readOnly: false
history: false
properties:
  user:
    type: relation
    title: user
    description: Description of the user input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 605c9480e9960e002c278191
    dependent: false
    primary: name
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 3
category: Singleplay
