_id: 607f3538ba6a15002c9120b8
name: 👑 NEW Login & Register
description: Login & Register with using fastlogin system of Turkcell
language: javascript
timeout: 63
triggers:
  login:
    options:
      method: Post
      path: /fastLogin
      preflight: true
    type: http
    active: true
  register:
    options:
      path: /fastRegister
      method: Post
      preflight: true
    type: http
    active: true
  testSeamlessTokenValidate:
    options:
      method: Get
      path: /testSeamlessTokenValidate
      preflight: true
    type: http
    active: true
  getMyIp:
    options:
      method: Get
      path: /getMyIp
      preflight: true
    type: http
    active: true
env:
  FASTLOGIN_SECRET_KEY: "{FASTLOGIN_SECRET_KEY}"
  FASTLOGIN_SERVICE_ID: "{FASTLOGIN_SERVICE_ID}"
  SECRET_API_KEY: "{SECRET_API_KEY}"
  USER_POLICY: "{USER_POLICY}"
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  PASSWORD_SALT: "{PASSWORD_SALT}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  TCELL_ADMIN_BUCKET_INSERT_APIKEY: "{TCELL_ADMIN_BUCKET_INSERT_APIKEY}"
memoryLimit: 100
order: 11
