_id: 6075942da04c51002d25547b
name: ❎ User Point Cleaner
description: Cleans users' weekly points
language: javascript
timeout: 20
triggers:
  clearUserPoint:
    options:
      timezone: Europe/Istanbul
      frequency: 0 0 * * 1
    type: schedule
    active: true
  setFreePlay15:
    options:
      timezone: Europe/Istanbul
      frequency: 0 0 15 * *
    type: schedule
    active: true
  detectError:
    options:
      method: Get
      path: /detectError
      preflight: true
    type: http
    active: true
  updateConfirmCode:
    options:
      timezone: Europe/Istanbul
      frequency: "* * * * *"
    type: schedule
    active: true
  manuallySendDrawFn:
    options:
      method: Get
      path: /manuallySendDrawFn
      preflight: true
    type: http
    active: true
env:
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  CONFIRMATION_CODE_BUCKET_ID: "{CONFIRMATION_CODE_BUCKET_ID}"
memoryLimit: 100
