_id: 61517461d0398a002e618021
title: Bots
description: bots bucket
icon: view_stream
primary: name
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  bot:
    type: boolean
    title: bot
    description: Description of the bot input
    options:
      position: bottom
    default: false
  avatar_color:
    type: string
    title: avatar_color
    description: Description of the avatar_color input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 12
