_id: 60c0d8d14ea46d002cb8d6f4
name: Mailer API
description: Manages your mail flow automatically
language: javascript
timeout: 83
triggers:
  default:
    options:
      bucket: 60c071bbb04bcc002c40f5c9
      type: INSERT
    type: bucket
    active: true
env:
  MAILER_API_KEY: "{MAILER_API_KEY}"
  TEMPLATES_BUCKET_ID: "{TEMPLATES_BUCKET_ID}"
  SMTP_USER: "{SMTP_USER}"
  SMTP_PASSWORD: "{SMTP_PASSWORD}"
  SMTP_HOST: "{SMTP_HOST}"
  MAIL_FROM: "{MAIL_FROM}"
  PAST_MATCHES_BUCKET_ID: "{PAST_MATCHES_BUCKET_ID}"
  MATCH_REPORT_BUCKET_ID: "{MATCH_REPORT_BUCKET_ID}"
  QUESTIONS_REPORT_BUCKET_ID: "{QUESTIONS_REPORT_BUCKET_ID}"
  CHARGE_REPORT_BUCKET_ID: "{CHARGE_REPORT_BUCKET_ID}"
  USERS_REPORT_BUCKET_ID: "{USERS_REPORT_BUCKET_ID}"
  USERS_MATCH_REPORT_BUCKET_ID: "{USERS_MATCH_REPORT_BUCKET_ID}"
  WIN_LOSE_MATCHES_BUCKET_ID: "{WIN_LOSE_MATCHES_BUCKET_ID}"
  ANSWERS_TO_QUESTION_REPORT_BUCKET_ID: "{ANSWERS_TO_QUESTION_REPORT_BUCKET_ID}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  SECRET_API_KEY: "{SECRET_API_KEY}"
  RETRY_REPORT_BUCKET_ID: "{RETRY_REPORT_BUCKET_ID}"
  REWARD_REPORT_BUCKET_ID: "{REWARD_REPORT_BUCKET_ID}"
memoryLimit: 100
