_id: 670e66f480e61c002b3e5a56
title: Single Play Past Matches
description: Describe your new bucket
icon: videogame_asset
primary: name
readOnly: false
history: false
properties:
  user:
    type: relation
    title: user
    description: Description of the user input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 605c9480e9960e002c278191
    dependent: false
    primary: name
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  user_point:
    type: number
    title: user_point
    description: Description of the user_point input
    options:
      position: bottom
  user_actions:
    type: array
    title: user_actions
    description: Description of the user_actions input
    options:
      position: bottom
    items:
      title: Title of the items
      type: string
  start_time:
    type: date
    title: start_time
    description: Description of the start_time input
    options:
      position: bottom
  end_time:
    type: date
    title: end_time
    description: Description of the end_time input
    options:
      position: bottom
  user_is_free:
    type: boolean
    title: user_is_free
    description: Description of the user_is_free input
    options:
      position: bottom
    default: false
  is_win:
    type: boolean
    title: is_win
    description: Description of the is_win input
    options:
      position: bottom
    default: false
acl:
  write: true==true
  read: true==true
order: 1
category: Singleplay
