_id: 60b624726c7ed4002c5b96e5
title: Alert
description: Describe your new bucket
icon: notification_important
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  message:
    type: textarea
    title: message
    description: Description of the message input
    options:
      position: bottom
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
    default: :created_at
acl:
  write: true==true
  read: true==true
order: 15
