_id: 606dc443782650002c0edbab
name: 💡 Answer to Question
description: This function works when the user is going to answer the current
  question in one`s duel.
language: javascript
timeout: 42
triggers:
  answerQuestion:
    options:
      method: Post
      path: /answerQuestion
      preflight: true
    type: http
    active: true
    batch:
      deadline: 35
      limit: 9007199254740991
env:
  DUEL_BUCKET_ID: "{DUEL_BUCKET_ID}"
  SECRET_API_KEY: "{SECRET_API_KEY}"
  DUEL_ANSWERS_BUCKET_ID: "{DUEL_ANSWERS_BUCKET_ID}"
  OPTIONS_BUCKET_ID: "{OPTIONS_BUCKET_ID}"
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  AFKCHECKER_API_KEY: "{AFKCHECKER_API_KEY}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  JWT_SECRET_KEY: "{JWT_SECRET_KEY}"
  PAST_DUELS_BUCKET_ID: "{PAST_DUELS_BUCKET_ID}"
  REWARD_BUCKET_ID: "{REWARD_BUCKET_ID}"
memoryLimit: 100
