_id: 670f6bc080e61c002b463d09
title: Corrupted Single Play Past Matches
description: Describe your new bucket
icon: assignment_late
primary: name
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  user:
    type: relation
    title: user
    description: Description of the user input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 605c9480e9960e002c278191
    dependent: false
    primary: name
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
  duel_object:
    type: textarea
    title: duel_object
    description: Description of the duel_object input
    options:
      position: bottom
  duel_data:
    type: string
    title: duel_data
    description: Description of the duel_data input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 2
category: Singleplay
