_id: 65732968066ea8002bf44b74
name: Adding msisdn to Contact Message
language: javascript
timeout: 132.2
triggers:
  onContactMessageInserted:
    type: bucket
    active: true
    options:
      bucket: 654cd7ee066ea8002bd964bd
      type: INSERT
  nullToUndefined:
    options:
      method: Get
      path: /nullToUndefined
      preflight: true
    type: http
    active: true
env:
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  CONTACT_MESSAGE_ID: "{CONTACT_MESSAGE_ID}"
  API_KEY: "{API_KEY}"
memoryLimit: 100
