_id: 676be83e4aa7f7002c3d6c9a
title: Retry Report Monthly
description: Describe your new bucket
icon: view_stream
primary: msisdn
readOnly: false
history: false
properties:
  msisdn:
    type: string
    title: msisdn
    description: Description of the msisdn input
    options:
      position: bottom
  retry_id:
    type: string
    title: retry_id
    description: Description of the retry_id input
    options:
      position: bottom
  retry_count:
    type: number
    title: retry_count
    description: Description of the retry_count input
    options:
      position: bottom
  retry_end_date:
    type: date
    title: retry_end_date
    description: Description of the retry_end_date input
    options:
      position: bottom
  charge_date:
    type: date
    title: charge_date
    description: Description of the charge_date input
    options:
      position: bottom
  is_success:
    type: boolean
    title: is_success
    description: Description of the is_success input
    options:
      position: bottom
    default: false
  error_id:
    type: string
    title: error_id
    description: Description of the error_id input
    options:
      position: bottom
  error_text:
    type: string
    title: error_text
    description: Description of the error_text input
    options:
      position: bottom
  process_time:
    type: number
    title: process_time
    description: Description of the process_time input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 49
