_id: 605c9480e9960e002c278191
title: User
description: User of an app
icon: account_circle
primary: name
readOnly: false
history: false
properties:
  identity:
    type: string
    title: identity
    description: Identity id of an user
    options:
      position: bottom
      index: true
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  profile_photo:
    type: storage
    title: profile_photo
    description: profile_photo of an user
    options:
      position: bottom
  perm_accept:
    type: boolean
    title: perm_accept
    description: perm_accept of an user
    options:
      position: bottom
    default: false
  elo:
    type: number
    title: elo
    description: Description of the elo input
    options:
      position: bottom
    minimum: 0
    default: 0
  bot:
    type: boolean
    title: bot
    description: if this user is bot or not
    options:
      position: bottom
    default: false
  total_point:
    type: number
    title: total_point
    description: Description of the total_point input
    options:
      position: bottom
    default: 0
  weekly_point:
    type: number
    title: weekly_point
    description: Description of the weekly_point input
    options:
      position: bottom
      index: true
    default: 0
  win_count:
    type: number
    title: win_count
    description: Description of the win_count input
    options:
      position: bottom
    default: 0
  lose_count:
    type: number
    title: lose_count
    description: Description of the lose_count input
    options:
      position: bottom
    default: 0
  free_play:
    type: boolean
    title: free_play
    description: Description of the free_play input
    options:
      position: bottom
    default: true
  available_play_count:
    type: number
    title: available_play_count
    description: Description of the available_play_count input
    options:
      position: bottom
    minimum: 0
    default: 0
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
      index: true
    default: :created_at
  total_award:
    type: number
    title: total_award
    description: Description of the total_award input
    options:
      position: bottom
    default: 0
    minimum: 0
  avatar_color:
    type: string
    title: avatar_color
    description: Description of the avatar_color input
    options:
      position: bottom
  note:
    type: textarea
    title: note
    description: Description of the note input
    options:
      position: bottom
  weekly_award:
    type: number
    title: weekly_award
    description: Description of the weekly_award input
    options:
      position: bottom
    default: 0
  draw_confirmated:
    type: boolean
    title: draw_confirmated
    description: Description of the draw_confirmated input
    options:
      position: bottom
    default: false
  op_note:
    type: array
    title: op_note
    description: Description of the op_note input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        sender:
          type: string
          title: sender
          description: Description of the sender input
          options:
            position: bottom
        note:
          type: textarea
          title: note
          description: Description of the note input
          options:
            position: bottom
        date:
          type: date
          title: date
          description: Description of the date input
          options:
            position: bottom
          default: :created_at
acl:
  write: |-
    auth.attributes.role == "admin" ||
    auth._id == "60a431c7a334b8002d50775e" ||
    auth.key == "e5wl18kmw287kr" ||
    auth.key == "27l17lnvl5996"
  read: true==true
required: []
order: 11
