_id: 616e99667db15e002d1e6e28
name: In Game
language: javascript
timeout: 53.7
triggers:
  changeName:
    type: http
    active: true
    options:
      method: Post
      path: /changeName
      preflight: true
env:
  SECRET_API_KEY: "{SECRET_API_KEY}"
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
memoryLimit: 100
