_id: 607e929910426d002ca337f0
name: ✨ Add to Match Making
description: Adding user to matchmaking bucket
language: javascript
timeout: 63
triggers:
  addMatchMaking:
    options:
      method: Post
      path: /addMatchMaking
      preflight: true
    type: http
    active: true
    batch:
      deadline: 55
      limit: 9007199254740991
env:
  MATCHMAKING_BUCKET_ID: "{MATCHMAKING_BUCKET_ID}"
  SECRET_API_KEY: "{SECRET_API_KEY}"
  JWT_SECRET_KEY: "{JWT_SECRET_KEY}"
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 10
