_id: 60742ed3f95e39002c4917ae
title: Past Matches
description: Describe your new bucket
icon: view_stream
primary: name
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  user1:
    type: relation
    title: user1
    description: Description of the user1 input
    options:
      position: bottom
      index: true
    relationType: onetoone
    bucketId: 605c9480e9960e002c278191
    dependent: false
    primary: name
  user2:
    type: relation
    title: user2
    description: Description of the user2 input
    options:
      position: bottom
      index: true
    relationType: onetoone
    bucketId: 605c9480e9960e002c278191
    dependent: false
    primary: name
  questions:
    type: array
    title: questions
    description: Description of the questions input
    options:
      position: bottom
    items:
      title: Title of the items
      type: textarea
  winner:
    type: number
    title: winner
    description: Description of the winner input
    options:
      position: bottom
  start_time:
    type: date
    title: start_time
    description: Description of the start_time input
    options:
      position: bottom
      index: true
  end_time:
    type: date
    title: end_time
    description: Description of the end_time input
    options:
      position: bottom
      index: true
  duel_id:
    type: string
    title: duel_id
    description: Description of the duel_id input
    options:
      position: bottom
      index: true
  player_type:
    type: number
    title: player_type
    description: This field indicates the type of players. (0 - P2P / 1 - P2M)
    options:
      position: bottom
    default: 0
    minimum: 0
    maximum: 1
  points_earned:
    type: number
    title: points_earned
    description: Description of the points_earned input
    options:
      position: bottom
    default: 0
  user1_is_free:
    type: boolean
    title: user1_is_free
    description: Description of the user1_is_free input
    options:
      position: bottom
      index: true
    default: false
  user2_is_free:
    type: boolean
    title: user2_is_free
    description: Description of the user2_is_free input
    options:
      position: bottom
      index: true
    default: false
    readOnly: false
acl:
  write: true == true
  read: true == true
order: 11
