_id: 625d2dfdbec610002c5540fb
name: Draw Functions
language: javascript
timeout: 59
triggers:
  sendChargeRequest:
    options:
      collection: bucket_60ab7235c03a2d002eb2f574
      type: INSERT
    type: database
    active: false
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  DRAW_LOGS_BUCKET: "{DRAW_LOGS_BUCKET}"
memoryLimit: 100
order: 21
