_id: 60c71d9ff30c8a002de746b9
name: Retry Reward
description: Retry Reward  Function
language: javascript
timeout: 143.7
triggers:
  checkReward:
    options:
      timezone: Europe/Istanbul
      frequency: "*/10 * * * *"
    type: schedule
    active: true
  detectUniqueCharges:
    options:
      method: Get
      path: /detectUniqueCharges
      preflight: true
    type: http
    active: true
  detectMissingAvailablePlay:
    options:
      timezone: Europe/Istanbul
      frequency: 0 * * * *
    type: schedule
    active: true
env:
  PAST_MATCHES_BUCKET_ID: "{PAST_MATCHES_BUCKET_ID}"
  REWARD_BUCKET_ID: "{REWARD_BUCKET_ID}"
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  MANUALLY_REWARD_BUCKET_ID: "{MANUALLY_REWARD_BUCKET_ID}"
  SECRET_API_KEY: "{SECRET_API_KEY}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  CHARGE_BUCKET_ID: "{CHARGE_BUCKET_ID}"
  PLAY_COUNT_LOGS_BUCKET_ID: "{PLAY_COUNT_LOGS_BUCKET_ID}"
  DELETED_MATCHES_BUCKET: "{DELETED_MATCHES_BUCKET}"
  BUGGED_REWARDS_BUCKET_ID: "{BUGGED_REWARDS_BUCKET_ID}"
  SINGLEPLAY_PAST_MATCHES_BUCKET_ID: "{SINGLEPLAY_PAST_MATCHES_BUCKET_ID}"
memoryLimit: 100
order: 17
